---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/status":
    get:
      summary: Check API status
      tags:
      - Status
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
